[package]
name = "dangerous"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
panic = 'abort'
strip = true

[dependencies]
libc = "0.2.146"
